show create table mt_store;

--
CREATE TABLE `mt_store`
(
    `ID`                 bigint      NOT NULL COMMENT 'ID',
    `MERCHANT_ID`        bigint               DEFAULT '0' COMMENT '商户ID',
    `NAME`               varchar(50) NOT NULL DEFAULT '' COMMENT '店铺名称',
    `QR_CODE`            varchar(255)         DEFAULT '' COMMENT '店铺二维码',
    `LOGO`               text COMMENT '店铺LOGO',
    `IS_DEFAULT`         char(1)     NOT NULL DEFAULT 'N' COMMENT '是否默认',
    `CONTACT`            varchar(30)          DEFAULT '' COMMENT '联系人姓名',
    `WX_MCH_ID`          varchar(30)          DEFAULT '' COMMENT '微信支付商户号',
    `WX_API_V2`          varchar(32)          DEFAULT '' COMMENT '微信支付APIv2密钥',
    `WX_CERT_PATH`       varchar(255)         DEFAULT '' COMMENT '微信支付证书',
    `ALIPAY_APP_ID`      varchar(100)         DEFAULT '' COMMENT '支付宝appId',
    `ALIPAY_PRIVATE_KEY` text COMMENT '支付宝应用私钥',
    `ALIPAY_PUBLIC_KEY`  text COMMENT '支付宝应用公钥',
    `PHONE`              varchar(20)          DEFAULT '' COMMENT '联系电话',
    `ADDRESS`            varchar(100)         DEFAULT '' COMMENT '地址',
    `LATITUDE`           varchar(30)          DEFAULT '' COMMENT '经度',
    `LONGITUDE`          varchar(30)          DEFAULT '' COMMENT '维度',
    `DISTANCE`           decimal(10, 2)       DEFAULT '0.00' COMMENT '距离',
    `HOURS`              varchar(255)         DEFAULT '' COMMENT '营业时间',
    `LICENSE`            varchar(255)         DEFAULT '' COMMENT '营业执照',
    `CREDIT_CODE`        varchar(50)          DEFAULT '' COMMENT '统一社会信用码',
    `BANK_NAME`          varchar(100)         DEFAULT '' COMMENT '银行名称',
    `BANK_CARD_NAME`     varchar(100)         DEFAULT '' COMMENT '银行卡账户名',
    `BANK_CARD_NO`       varchar(100)         DEFAULT '' COMMENT '银行卡卡号',
    `DESCRIPTION`        varchar(2000)        DEFAULT '' COMMENT '备注信息',
    `CREATE_TIME`        datetime             DEFAULT NULL COMMENT '创建时间',
    `UPDATE_TIME`        datetime             DEFAULT NULL COMMENT '更新时间',
    `STATUS`             char(1)              DEFAULT 'A' COMMENT '状态，A：有效/启用；D：无效',
    `OPERATOR`           varchar(30)          DEFAULT '' COMMENT '最后操作人',
    `up_flag`            int                  DEFAULT '0' COMMENT '0 未上传 1 上传中 2 已上传',
    `up_count`           int                  DEFAULT '0' COMMENT '上传次数',
    `up_msg`             varchar(255)         DEFAULT NULL COMMENT '上传信息',
    `up_id`              varchar(255)         DEFAULT NULL COMMENT '上传ID',
    `zn_device_sn_var`   varchar(255)         DEFAULT NULL COMMENT '设备编号',
    `remark`             varchar(100)         DEFAULT NULL COMMENT '备注',
    `del_flag`           tinyint              DEFAULT '0' COMMENT '删除标识',
    `create_id`          bigint               DEFAULT NULL COMMENT '创建者ID',
    `create_by`          varchar(50)          DEFAULT NULL COMMENT '创建者',
    `update_id`          bigint               DEFAULT NULL COMMENT '更新者ID',
    `update_by`          varchar(50)          DEFAULT NULL COMMENT '更新者',
    `create_dept`        bigint               DEFAULT NULL COMMENT '创建者部门',
    PRIMARY KEY (`ID`) USING BTREE
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb3 COMMENT ='店铺表';