version: '3.7'
# 设置nginx服务
services:
  nginx:
    container_name: nginx1232
    image: nginx:1.23.2
    restart: always
    build:
      context: ./
    ports:
      - "80:80"
    volumes:
      - /home/everforcc/data/nginx/nginx80/html:/usr/share/nginx/html
      - /home/everforcc/data/nginx/nginx80/conf/nginx.conf:/etc/nginx/nginx.conf
      - /home/everforcc/data/nginx/nginx80/logs:/var/log/nginx
    environment:
      # 设置时区为上海，否则时间会有问题
      - TZ=Asia/Shanghai