version: '3.7'
# 设置nginx服务
services:
  nginx:
    container_name: nginx1232
    image: nginx:1.23.2
    restart: always
    ports:
      - 80:80
    volumes:
      - /home/data/nginx/nginx80/html:/usr/share/nginx/html
      - /home/data/nginx/nginx80/conf:/etc/nginx
      - /home/data/nginx/nginx80/logs:/var/log/nginx
    environment:
      - TZ=Asia/Shanghai
    network_mode: host
