version : '3.8'

services:
  minio:
    image: minio/minio:RELEASE.2023-12-23T07-19-11Z
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    deploy:
      resources:
        limits:
          memory: 500M
        reservations:
          memory: 500M
    environment:
      TZ: Asia/Shanghai
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: root
      MINIO_COMPRESS: "off"
      MINIO_COMPRESS_EXTENSIONS: ""
      MINIO_COMPRESS_MIME_TYPES: ""
    build:
      context: ./minio
    volumes:
      - /data/smartparklocal-data/minio/data:/data
      - /data/smartparklocal-data/minio/config:/root/.minio/
    command: server --address ':9000' --console-address ':9001' /data  # 指定容器中的目录 /data
    privileged: true
