version : '3.8'

services:
  minio:
    image: quay.io/minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    deploy:
      resources:
        limits:
          memory: 600M # 限制内存使用
        reservations: # 为容器预留的资源
          memory: 200M
    environment:
      TZ: Asia/Shanghai
      MINIO_ROOT_USER: rootc.c.
      MINIO_ROOT_PASSWORD: rootc.c.
      MINIO_COMPRESS: "off"
      MINIO_COMPRESS_EXTENSIONS: ""
      MINIO_COMPRESS_MIME_TYPES: ""
    build:
      context: ./minio
    volumes:
      - /data/project-data/minio/data:/data
      - /data/project-data/minio/config:/root/.minio/
    command: server --address ':9000' --console-address ':9001' /data  # 指定容器中的目录 /data
    privileged: true
