ALTER TABLE `mt_cart` ADD `IS_SINGLE_SPEC` CHAR(1) NOT NULL DEFAULT 'Y' COMMENT '是否单规格';

ALTER TABLE `mt_cart` ADD `WEIGHT` DECIMAL(10,2) DEFAULT '0.00' COMMENT '重量';

ALTER TABLE `mt_order_goods` ADD `WEIGHT` DECIMAL(10,2) DEFAULT '0.00' COMMENT '重量';

-- 卡券新增关联商品字段
-- ALTER TABLE `mt_coupon` ADD `WEIGHT` DECIMAL(10,2) DEFAULT '0.00' COMMENT '重量';