-- auto-generated definition
create table zn_lkl_merchant_msg
(
    id                        bigint auto_increment comment '唯一标识'
        primary key,
    user_id                   bigint                                 null comment '用户id',
    type                      varchar(10)                            null comment '1 小微 2 企业',
    user_name                 varchar(100)                           null comment '用户姓名',
    user_card_no              varchar(100)                           null comment '用户身份证号码',
    user_card_start_time      varchar(20)                            null comment '身份证 开始时间 年-月-日',
    user_card_end_time        varchar(20)                            null comment '身份证 结束时间 年-月-日',
    user_card_effect          varchar(10)                            null comment '长期有效 1:长期有效 0:非长期有效',
    user_phone                varchar(20)                            null comment '用户手机号',
    user_email                varchar(100)                           null comment '邮箱',
    company_name              varchar(200)                           null comment '公司名称',
    province_code             varchar(20)                            null comment '获取地区信息_树结构.json 省份code',
    city_code                 varchar(20)                            null comment '获取地区信息_树结构.json 城市code',
    county_code               varchar(20)                            null comment '获取地区信息_树结构.json 区县 code',
    company_address_detail    varchar(200)                           null comment '公司地址 详细地址',
    company_type              varchar(100)                           null comment '获取小类.json 公司类型',
    company_code              varchar(100)                           null comment '获取小类.json 公司类型 code',
    business_content          varchar(500)                           null comment '主营业务',
    bank_card_url             varchar(255)                           null comment '银行卡地址',
    bank_card_url_lkl         varchar(255)                           null comment '银行卡地址lkl',
    bank_card_no              varchar(100)                           null comment '银行卡号',
    bank_card_open_city_code  varchar(100)                           null comment '银行卡开户行 code 银行列表查询_分组.json branch_bank_no',
    bank_card_open_city_name  varchar(100)                           null comment '银行卡开户行 银行列表查询_分组.json branch_bank_name',
    bank_card_clearing_code   varchar(100)                           null comment '结算账户清算行号 json的 clearNo 字段 银行列表查询_分组.json clear_no',
    bank_card_province_code   varchar(100)                           null comment '银行地区_树结构.json 银行开户省份 code',
    bank_card_province_name   varchar(100)                           null comment '银行地区_树结构.json 银行开户省份 name',
    bank_card_city_name       varchar(100)                           null comment '银行地区_树结构.json 银行卡开户城市',
    bank_card_city_code       varchar(100)                           null comment '银行地区_树结构.json 银行卡开户城市 code',
    user_card_front_url       varchar(512)                           null comment '用户身份证正面链接',
    user_card_front_url_lkl   varchar(512)                           null comment '用户身份证正面链接lkl fileType = ID_CARD_FRONT',
    user_card_back_url        varchar(512)                           null comment '用户身份证反面链接',
    user_card_back_url_lkl    varchar(512)                           null comment '用户身份证反面链接lkl fileType = ID_CARD_BEHIND',
    company_header_url        varchar(512)                           null comment '门头照',
    company_header_url_lkl    varchar(512)                           null comment '门头照 lkl fileType = SHOP_OUTSIDE_IMG',
    company_in_door_url       varchar(512)                           null comment '内部照',
    company_in_door_url_lkl   varchar(512)                           null comment '内部照 lkl fileType = SHOP_INSIDE_IMG',
    company_cashier_url       varchar(512)                           null comment '收银台',
    company_cashier_url_lkl   varchar(512)                           null comment '收银台 lkl fileType = CHECKSTAND_IMG',
    company_other_url         varchar(512)                           null comment '其他补充照片',
    company_other_url_lkl     varchar(512)                           null comment '其他补充照片 lkl fileType = OTHERS',
    remark                    text                                   null comment '备注',
    create_id                 bigint                                 null comment '创建者ID',
    create_by                 varchar(64) charset utf8mb4 default '' null comment '创建者',
    create_time               datetime                               null comment '创建时间',
    create_dept               bigint                                 null comment '创建部门',
    update_id                 bigint                                 null comment '更新者ID',
    update_by                 varchar(64) charset utf8mb4 default '' null comment '更新者',
    update_time               datetime                               null comment '更新时间',
    del_flag                  tinyint(1)                  default 0  null comment '删除标志（0代表存在 1代表删除）',
    business_license_name     varchar(100)                           null comment '营业执照名称',
    business_license_code     varchar(100)                           null comment '营业执照代码',
    business_license_dt_start varchar(20)                            null comment '营业执照开始时间',
    business_license_dt_end   varchar(20)                            null,
    business_licence_url      varchar(512)                           null comment '营业执照url',
    business_licence_url_lkl  varchar(512)                           null comment '营业执照url lkl',
    opening_permit_url        varchar(512)                           null comment '开户许可证url',
    opening_permit_url_lkl    varchar(512)                           null comment '开户许可证url lkl'
)
    comment 'LKL 进件信息' collate = utf8mb4_unicode_ci;

