show create table mt_coupon;

--
CREATE TABLE `mt_coupon`
(
    `ID`               bigint       NOT NULL COMMENT 'ID',
    `MERCHANT_ID`      bigint                DEFAULT '0' COMMENT '商户ID',
    `store_id`         bigint                DEFAULT '0' COMMENT '店铺ID',
    `GROUP_ID`         int          NOT NULL DEFAULT '0' COMMENT '券组ID',
    `TYPE`             char(1)               DEFAULT 'C' COMMENT '券类型，C优惠券；P预存卡；T集次卡',
    `NAME`             varchar(100) NOT NULL DEFAULT '' COMMENT '券名称',
    `IS_GIVE`          tinyint(1)            DEFAULT '0' COMMENT '是否允许转赠',
    `GRADE_IDS`        varchar(100)          DEFAULT '' COMMENT '适用会员等级',
    `POINT`            int                   DEFAULT '0' COMMENT '获得卡券所消耗积分',
    `APPLY_GOODS`      varchar(20)           DEFAULT '' COMMENT '适用商品：allGoods、parkGoods',
    `RECEIVE_CODE`     varchar(32)           DEFAULT '' COMMENT '领取码',
    `USE_FOR`          varchar(30)           DEFAULT '' COMMENT '使用专项',
    `EXPIRE_TYPE`      varchar(30)           DEFAULT '' COMMENT '过期类型',
    `EXPIRE_TIME`      int                   DEFAULT '0' COMMENT '有效期，单位：天',
    `BEGIN_TIME`       datetime              DEFAULT NULL COMMENT '开始有效期',
    `END_TIME`         datetime              DEFAULT NULL COMMENT '结束有效期',
    `AMOUNT`           decimal(10, 2)        DEFAULT '0.00' COMMENT '面额',
    `SEND_WAY`         varchar(20)           DEFAULT 'backend' COMMENT '发放方式',
    `SEND_NUM`         int unsigned          DEFAULT '1' COMMENT '每次发放数量',
    `TOTAL`            int                   DEFAULT '0' COMMENT '发行数量',
    `LIMIT_NUM`        int                   DEFAULT '1' COMMENT '每人拥有数量限制',
    `EXCEPT_TIME`      varchar(500)          DEFAULT '' COMMENT '不可用日期，逗号隔开。周末：weekend；其他：2019-01-02_2019-02-09',
    `STORE_IDS`        varchar(100)          DEFAULT '' COMMENT '所属店铺ID,逗号隔开',
    `DESCRIPTION`      varchar(2000)         DEFAULT '' COMMENT '描述信息',
    `IMAGE`            varchar(100)          DEFAULT '' COMMENT '效果图片',
    `REMARKS`          varchar(1000)         DEFAULT '' COMMENT '后台备注',
    `IN_RULE`          varchar(1000)         DEFAULT '' COMMENT '获取券的规则',
    `OUT_RULE`         varchar(1000)         DEFAULT '' COMMENT '核销券的规则',
    `CREATE_TIME`      datetime              DEFAULT NULL COMMENT '创建时间',
    `UPDATE_TIME`      datetime              DEFAULT NULL COMMENT '更新时间',
    `OPERATOR`         varchar(30)           DEFAULT '' COMMENT '最后操作人',
    `STATUS`           char(1)               DEFAULT 'A' COMMENT 'A：正常；D：删除',
    `up_flag`          int                   DEFAULT '0' COMMENT '0 未上传 1 上传中 2 已上传',
    `up_count`         int                   DEFAULT '0' COMMENT '上传次数',
    `up_msg`           varchar(255)          DEFAULT NULL COMMENT '上传信息',
    `up_id`            varchar(255)          DEFAULT NULL COMMENT '上传ID',
    `zn_device_sn_var` varchar(255)          DEFAULT NULL COMMENT '设备编号',
    `remark`           varchar(100)          DEFAULT NULL COMMENT '备注',
    `del_flag`         tinyint               DEFAULT '0' COMMENT '删除标识',
    `create_id`        bigint                DEFAULT NULL COMMENT '创建者ID',
    `create_by`        varchar(50)           DEFAULT NULL COMMENT '创建者',
    `update_id`        bigint                DEFAULT NULL COMMENT '更新者ID',
    `update_by`        varchar(50)           DEFAULT NULL COMMENT '更新者',
    `create_dept`      bigint                DEFAULT NULL COMMENT '创建者部门',
    PRIMARY KEY (`ID`) USING BTREE
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb3 COMMENT ='卡券信息表';