STOP SLAVE FOR CHANNEL 'slave2';
RESET SLAVE FOR CHANNEL 'slave2';

CHANGE MASTER TO
    MASTER_HOST='mysql-slave2',
    MASTER_PORT=3306,
    MASTER_USER='repl_user',
    MASTER_PASSWORD='repl_pass',
    MASTER_AUTO_POSITION=1
    FOR CHANNEL 'slave2';

START SLAVE FOR CHANNEL 'slave2';
