version: '3.7'

services:
  redis5201:
    image: 'redis:6.2.5'
    container_name: redis5201
    network_mode: host
    restart: always
    ports:
      - 5201:5201
    command:
      ["redis-server", "/usr/local/etc/redis/redis.conf"]
    volumes:
      - /mnt/hkzk/redis/redis5201/conf/redis5201.conf:/usr/local/etc/redis/redis.conf
      - /mnt/hkzk/redis/redis5201/data:/data
    environment:
      # 设置时区为上海，否则时间会有问题
      - TZ=Asia/Shanghai
