version: '3.7'

services:
  nacos:
    container_name: nacos220c3
    network_mode: host
    image: nacos/nacos-server:2.2.0
    environment:
      - TZ=Asia/Shanghai
      - NACOS_AUTH_ENABLE=true
    volumes:
      - /mnt/hkzk/nacos/cluster/c3/logs/:/home/nacos/logs
      - /mnt/hkzk/nacos/cluster/c3/conf/application.properties:/home/nacos/conf/application.properties
      - /mnt/hkzk/nacos/cluster/c3/conf/cluster.conf:/home/nacos/conf/cluster.conf

