-- auto-generated definition
create table zn_pay_huifu_msg
(
    id                         bigint                 not null comment '主键',
    auth_type                  varchar(1)             null comment '1 企业商户 2 个人商户',
    upper_huifu_id             varchar(18)            null comment '上级汇付id',
    reg_name                   varchar(32)            null comment '店铺名',
    short_name                 varchar(32)            null,
    receipt_name               varchar(255)           null,
    scene_type                 varchar(32)            null comment 'ONLINE：线上场景；OFFLINE：线下场景；ALL：线上线下',
    prov_id                    varchar(6)             null comment '经营省',
    prov                       varchar(20)            null comment '省',
    area_id                    varchar(6)             null comment '经营市',
    area                       varchar(20)            null comment '市',
    district_id                varchar(6)             null comment '经营区',
    district                   varchar(20)            null comment '区',
    detail_addr                varchar(256)           null comment '经营详细地址',
    legal_addr                 varchar(256)           null comment '法人证件地址',
    legal_cert_back_pic        varchar(64)            null comment '法人身份证国徽面',
    legal_cert_back_pic_url    varchar(500)           null comment '法人身份证国徽面url',
    legal_cert_front_pic       varchar(64)            null comment '法人身份证人像面',
    legal_cert_front_pic_url   varchar(500)            null comment '法人身份证人像面url',
    contact_name               varchar(32)            null comment '联系人姓名',
    contact_mobile_no          varchar(11)            null comment '联系人手机号',
    contact_email              varchar(32)            null comment '联系人电子邮箱',
    login_name                 varchar(32)            null comment '管理员账号',
    legal_cert_validity_type   varchar(1)             null comment '负责人证件有效期类型 1：长期有效；0：非长期有效',
    legal_cert_begin_date      varchar(8)             null comment '身份证开始时间',
    legal_cert_end_date        varchar(8)             null comment '身份证结束时间',
    legal_cert_no              varchar(32)            null comment '负责人证件号码',
    mcc                        varchar(7)             null comment '商户所属行业',
    store_header_pic           varchar(64)            null comment '线下经营-店铺门头照',
    store_header_pic_url       varchar(500)           null comment '线下经营-店铺门头照',
    store_indoor_pic           varchar(64)            null comment '线下经营-店铺内景/工作区域照',
    store_indoor_pic_url       varchar(500)           null comment '线下经营-店铺内景/工作区域照',
    store_cashier_desk_pic     varchar(64)            null comment '线下经营-店铺收银台/公司前台照',
    store_cashier_desk_pic_url varchar(500)           null comment '线下经营-店铺收银台/公司前台照',
    card_name                  varchar(128)           null comment '银行账户名',
    card_no                    varchar(32)            null comment '银行账号',
    card_prov_id               varchar(6)             null comment '银行所在省',
    card_area_id               varchar(6)             null comment '银行所在市',
    card_cert_type             varchar(2)             null comment '持卡人证件类型',
    card_cert_no               varchar(32)            null comment '持卡人证件号码',
    card_cert_validity_type    varchar(1)             null comment '持卡人证件有效期类型',
    card_cert_begin_date       varchar(8)             null comment '持卡人证件有效期开始',
    card_cert_end_date         varchar(8)             null comment '持卡人证件有效期截止日期',
    settle_cycle               varchar(2)             null comment '结算周期',
    settle_pattern             varchar(50)            null comment '结算方式',
    settle_batch_no            varchar(16)            null comment '结算批次号',
    remark                     varchar(255)           null comment '备注',
    create_id                  bigint                 null comment '创建者ID',
    create_by                  varchar(64) default '' null comment '创建者',
    create_time                datetime               null comment '创建时间',
    create_dept                bigint                 null comment '创建部门',
    update_id                  bigint                 null comment '更新者ID',
    update_by                  varchar(64) default '' null comment '更新者',
    update_time                datetime               null comment '更新时间',
    del_flag                   tinyint(1)  default 0  null,
    constraint zn_pay_huifu_msg_id_uindex
        unique (id)
)
    comment '上传给汇付的信息';

alter table zn_pay_huifu_msg
    add primary key (id);

