-- STOP SLAVE FOR CHANNEL 'slave1';


CHANGE MASTER TO
    MASTER_HOST='mysql-slave1',
    MASTER_PORT=3306,
    MASTER_USER='repl_user',
    MASTER_PASSWORD='repl_pass',
    MASTER_AUTO_POSITION=1
    FOR CHANNEL 'slave1';

START SLAVE FOR CHANNEL 'slave1';
