version: '3.7'
# 设置nginx服务
services:
  nacos:
    container_name: nacos220
    image: nacos/nacos-server:2.2.0
    build:
      context: ./
    environment:
      - MODE=standalone
    volumes:
      - ./nacos/logs/:/home/nacos/logs
      - ./nacos/conf/application.properties:/home/nacos/conf/application.properties
    ports:
      - "8848:8848"
      - "9848:9848"
      - "9849:9849"
