version: '3.7'

services:
  nacos:
    container_name: nacos220
    image: nacos/nacos-server:2.2.0
    build:
      context: ./
    environment:
      - MODE=standalone
      - TZ=Asia/Shanghai
    volumes:
      - /mnt/hkzk/nacos/single/logs/:/home/nacos/logs
      - /mnt/hkzk/nacos/single/conf/application.properties:/home/nacos/conf/application.properties
    ports:
      - "8848:8848"
      - "9848:9848"
      - "9849:9849"
