# 基础镜像
#FROM  openjdk:8-jre
FROM  eclipse-temurin:17.0.10_7-jdk-centos7
# author
MAINTAINER ruoyi

# 挂载目录
VOLUME /home/ruoyi
# 创建目录
RUN mkdir -p /home/ruoyi
# 指定路径
WORKDIR /home/ruoyi
# 复制jar文件到路径
COPY ./jar/ruoyi-dm-cli.jar /home/ruoyi/ruoyi-dm-cli.jar
# 启动认证服务
ENTRYPOINT ["java","-jar","ruoyi-dm-cli.jar"]

