-- 1. 查看创建脚本
show create table mt_merchant;

-- 2. 组装关联商户id脚本
SELECT concat('ALTER TABLE ', TABLE_NAME, ' MODIFY `MERCHANT_ID` bigint  DEFAULT ''0'' COMMENT ''商户ID'';') as s
FROM INFORMATION_SCHEMA.Columns
WHERE COLUMN_NAME = 'merchant_id';

-- 3. modify脚本
ALTER TABLE mt_article MODIFY `MERCHANT_ID` bigint  DEFAULT '0' COMMENT '商户ID';
ALTER TABLE mt_balance MODIFY `MERCHANT_ID` bigint  DEFAULT '0' COMMENT '所属商户ID';
ALTER TABLE mt_banner MODIFY `MERCHANT_ID` bigint  DEFAULT '0' COMMENT '所属商户ID';
ALTER TABLE mt_book MODIFY `MERCHANT_ID` bigint  DEFAULT '0' COMMENT '商户ID';
ALTER TABLE mt_book_item MODIFY `MERCHANT_ID` bigint  DEFAULT '0' COMMENT '商户ID';
ALTER TABLE mt_cart MODIFY `MERCHANT_ID` bigint  DEFAULT '0' COMMENT '商户ID';
ALTER TABLE mt_commission_cash MODIFY `MERCHANT_ID` bigint  DEFAULT '0' COMMENT '商户ID';
ALTER TABLE mt_commission_log MODIFY `MERCHANT_ID` bigint  DEFAULT '0' COMMENT '商户ID';
ALTER TABLE mt_commission_relation MODIFY `MERCHANT_ID` bigint  DEFAULT '0' COMMENT '商户ID';
ALTER TABLE mt_commission_rule MODIFY `MERCHANT_ID` bigint  DEFAULT '0' COMMENT '商户ID';
ALTER TABLE mt_commission_rule_item MODIFY `MERCHANT_ID` bigint  DEFAULT '0' COMMENT '商户ID';
ALTER TABLE mt_confirm_log MODIFY `MERCHANT_ID` bigint  DEFAULT '0' COMMENT '商户ID';
ALTER TABLE mt_coupon MODIFY `MERCHANT_ID` bigint  DEFAULT '0' COMMENT '商户ID';
ALTER TABLE mt_coupon_group MODIFY `MERCHANT_ID` bigint  DEFAULT '0' COMMENT '商户ID';
ALTER TABLE mt_freight MODIFY `MERCHANT_ID` bigint  DEFAULT '0' COMMENT '商户ID';
ALTER TABLE mt_give MODIFY `MERCHANT_ID` bigint  DEFAULT '0' COMMENT '商户ID';
ALTER TABLE mt_goods MODIFY `MERCHANT_ID` bigint  DEFAULT '0' COMMENT '所属商户ID';
ALTER TABLE mt_goods_cate MODIFY `MERCHANT_ID` bigint  DEFAULT '0' COMMENT '商户ID';
ALTER TABLE mt_message MODIFY `MERCHANT_ID` bigint  DEFAULT '0' COMMENT '商户ID';
ALTER TABLE mt_open_gift MODIFY `MERCHANT_ID` bigint  DEFAULT '0' COMMENT '商户ID';
ALTER TABLE mt_order MODIFY `MERCHANT_ID` bigint  DEFAULT '0' COMMENT '商户ID';
ALTER TABLE mt_point MODIFY `MERCHANT_ID` bigint  DEFAULT '0' COMMENT '商户ID';
ALTER TABLE mt_printer MODIFY `MERCHANT_ID` bigint  DEFAULT '0' COMMENT '商户ID';
ALTER TABLE mt_refund MODIFY `MERCHANT_ID` bigint  DEFAULT '0' COMMENT '商户ID';
ALTER TABLE mt_send_log MODIFY `MERCHANT_ID` bigint  DEFAULT '0' COMMENT '商户ID';
ALTER TABLE mt_setting MODIFY `MERCHANT_ID` bigint  DEFAULT '0' COMMENT '商户ID';
ALTER TABLE mt_settlement MODIFY `MERCHANT_ID` bigint  DEFAULT '0' COMMENT '商户ID';
ALTER TABLE mt_sms_sended_log MODIFY `MERCHANT_ID` bigint  DEFAULT '0' COMMENT '商户ID';
ALTER TABLE mt_sms_template MODIFY `MERCHANT_ID` bigint  DEFAULT '0' COMMENT '商户ID';
ALTER TABLE mt_staff MODIFY `MERCHANT_ID` bigint  DEFAULT '0' COMMENT '商户ID';
ALTER TABLE mt_stock MODIFY `MERCHANT_ID` bigint  DEFAULT '0' COMMENT '商户ID';
ALTER TABLE mt_store MODIFY `MERCHANT_ID` bigint  DEFAULT '0' COMMENT '商户ID';
ALTER TABLE mt_table MODIFY `MERCHANT_ID` bigint  DEFAULT '0' COMMENT '商户ID';
ALTER TABLE mt_user MODIFY `MERCHANT_ID` bigint  DEFAULT '0' COMMENT '商户ID';
ALTER TABLE mt_user_action MODIFY `MERCHANT_ID` bigint  DEFAULT '0' COMMENT '商户ID';
ALTER TABLE mt_user_coupon MODIFY `MERCHANT_ID` bigint  DEFAULT '0' COMMENT '商户ID';
ALTER TABLE mt_user_grade MODIFY `MERCHANT_ID` bigint  DEFAULT '0' COMMENT '商户ID';
ALTER TABLE mt_user_group MODIFY `MERCHANT_ID` bigint  DEFAULT '0' COMMENT '商户ID';
ALTER TABLE t_account MODIFY `MERCHANT_ID` bigint  DEFAULT '0' COMMENT '商户ID';
ALTER TABLE t_action_log MODIFY `MERCHANT_ID` bigint  DEFAULT '0' COMMENT '商户ID';
ALTER TABLE t_duty MODIFY `MERCHANT_ID` bigint  DEFAULT '0' COMMENT '商户ID';
ALTER TABLE t_source MODIFY `MERCHANT_ID` bigint  DEFAULT '0' COMMENT '商户ID';

