version: '3.7'

services:
  nacos:
    container_name: nacos220c2
    network_mode: host
    restart: always
    image: nacos/nacos-server:2.2.0
    environment:
      - TZ=Asia/Shanghai
      - NACOS_AUTH_ENABLE=true
    volumes:
      - /mnt/hkzk/nacos/cluster/c2/logs/:/home/nacos/logs
    env_file:
      - nacos-cluster.env