version: '3.7'

services:
  nacos:
    container_name: nacos220single
    image: nacos/nacos-server:2.2.0
    build:
      context: .
    environment:
      - MODE=standalone
      - TZ=Asia/Shanghai
    volumes:
      - /mnt/hkzk/nacos/single/logs/:/home/nacos/logs
      - /mnt/hkzk/nacos/single/conf/application.properties:/home/nacos/conf/application.properties
    ports:
      - "8858:8848"
      - "9858:9848"
      - "9859:9849"
