version : '3.8'
services:
  mysqlmaster:
    container_name: mysql57master
    network_mode: bridge
    restart: always
    image: mysql:5.7
    build:
      context: ./
    ports:
      - "3310:3306"
    volumes:
      - /path/mysql/master/conf:/etc/mysql/conf.d
      - /path/mysql/master/logs:/logs
      - /path/mysql/master/data:/var/lib/mysql
#      - /path/mysql/backup:/path/mysql/backup
#      - /var/spool/cron/crontabs:/var/spool/cron/crontabs
    command: [
        'mysqld',
        '--server-id=1',
        '--log-bin=mysql-bin',
        '--expire_logs_days=10',
        '--binlog-do-db=oneforall',
        '--innodb-buffer-pool-size=80M',
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci',
        '--default-time-zone=+8:00',
        '--lower-case-table-names=1'
    ]
    environment:
      #MYSQL_DATABASE: 'oneforall'
      MYSQL_ROOT_PASSWORD: ccdevmasterroot